### ISSUE TITLE
Cannot compile sodata

### ISSUE THREAD

**Issue by masud-technope** [sth/sodata#6]
I was trying to compile, and found the error.

`make csvimport`
```
g++ -O2 -ggdb -Wall -c soimport.cpp
In file included from soimport.hpp:5:0,
                 from soimport.cpp:2:
xmldb.hpp:6:19: fatal error: expat.h: No such file or directory

                   ^
compilation terminated.
make: *** [soimport.o] Error 1
```
Please help.

**Comment by sth** [comment]
The program uses `libexpat` to parse the XML files. The library and the its header files need to be installed so that they can be found by the compiler. On Ubuntu or a similar Debian based system you would install the required files like this:

    sudo apt install libexpat1 libexpat1-dev

I have improved the README file to be more helpful for installing the required dependencies.
